---
  sudo: required

  env:
    global:
      - DOCKER_COMPOSE_VERSION=1.22.0
      - DOCKER_IMAGE=mlr-legacy-transformer
  jobs:
    include:
      - name: coverage
        language: python
        python:
          - "3.6"
        install:
          - pip install -r requirements.txt
          - pip install coverage
          - pip install coveralls
        script:
          - coverage run --omit=tests/*.py,/home/travis/virtualenv/* -m unittest
          - coveralls